### ISSUE TITLE
Unordered scoreboard

### ISSUE THREAD

**Issue by rkkautsar** [adamyordan/PlatformCTFNetsos#2]
![2016-03-26_21 33 10](https://cloud.githubusercontent.com/assets/1536976/14060544/6bfdf940-f39a-11e5-9d69-cc586f3dab27.png)

**Comment by rkkautsar** [comment]
This happens on routes:
- `/contest/{contest}`
- `/`

**Comment by adamyordan** [comment]
resolved in commit f201286
