### ISSUE TITLE
add problemsetter as user type

### ISSUE THREAD

**Issue by wirabdillah** [adamyordan/PlatformCTFNetsos#5]
I suggest adding problemsetter as new user type.
Problemsetter can do:
- Add Contest.
- Add other problemsetters as Contributor.
- Problemsetter can only add and edit problem in their own contest.

**Comment by wirabdillah** [comment]
Because no one use this platform anymore, i will close this issue.

**Comment by adamyordan** [comment]
let's delete this repo

**Comment by wirabdillah** [comment]
i think it's better to archive this repo than delete it. Maybe some code will be useful in the future :rocket:
